name: Bug Fix 🐛
description: 버그 수정을 위한 이슈 제출
title: "[RID-@@@][fix]: Please write title "
labels: [":rocket: fix"]
body:
  - type: textarea
    attributes:
      label: 체크리스트
      description: 이슈 제출 전에 반드시 아래 체크리스트를 확인하세요
      value: |
        - [ ] 나는 linear에 해당 이슈를 작업하기 위한 백로그가 존재하는지 확인했다.
        - [ ] 나는 이슈 제목에 RID 번호를 적었다.
  - type: textarea
    id: description
    attributes:
      label: 목적
      description: 수정하고자하는 버그에 대해 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 기능 명세
      description: 버그를 수정하기 위해 어떤 해결책이 존재하는지 기재해주세요.
    validations:
      required: false
