
name: PR Test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'

      - name: Setup key
        id: setup-key
        env:
          PRIVATE_KEY: ${{ secrets.CLOUD_FRONT_PRIVATE_KEY }}
        run: |
          touch ./src/main/resources/key.pem
          echo "$PRIVATE_KEY" >> "./src/main/resources/key.pem"
          chmod 400 "./src/main/resources/key.pem"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        env:
          RDS_URL: ${{ secrets.RDS_URL }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SQS_QUEUE_NAME: ${{ secrets.AWS_SQS_QUEUE_NAME }}
          AWS_SQS_QUEUE_URL: ${{ secrets.AWS_SQS_QUEUE_URL }}
          AWS_REGION: ap-northeast-2
          SLACK_CLIENT_ID: temp
          SLACK_CLIENT_SECRET: temp
          SLACK_REDIRECT_URL: temp
          SLACK_BOT_TOKEN: temp
          DDL_AUTO: update
          ENVIRONMENT: build
          AWS_S3_BUCKET: temp
          AWS_CLOUDFRONT_URL: temp
          AWS_CLOUDFRONT_KEYPAIR: temp
          TEST_ENVIRONMENT: data-build
        run: |
          echo $ENVIRONMENT
          ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml
