
name: PR Test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'

      - name: Set up application.properties
        run: |
          touch ./src/main/resources/application-build.properties
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-build.properties

      - name: Set up application-data.properties
        run: |
          touch ./src/test/resources/application-data.properties
          echo "${{ secrets.APPLICATION_DATA }}" > ./src/test/resources/application-data.properties

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: |
          echo "ENVIRONMENT=build" >> $GITHUB_ENV
          echo $ENVIRONMENT
          ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml